import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ShortenForm from '../components/ShortenForm';
import Footer from '../components/Footer';

const Home: NextPage = () => {
  return (
    <div className="className='sm:p-8 px-4 py-8 w-full bg-black min-h-[calc(100vh-73px)]'">
      <Head>
        <title>Scissor : URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl">Scissor URL Shortener</h1>
      </main>
      <ShortenForm />
      <Footer />
    </div>
  );
};

export default Home;
