import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ShortenForm from '../components/ShortenForm';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Scissor : URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Scissor URL Shortener</h1>
      </main>
      <ShortenForm />
      <footer className={styles.footer}>2023</footer>
    </div>
  );
};

export default Home;
